ROOT = ""

SAMPLES = f"{ ROOT }RV/samples"
RECORDED = f"{ ROOT }RV/grabado"
RECORDED_RAW = f"{ ROOT }RV/grabado/grabado_raw.wav"
RECORDED_PROC = f"{ ROOT }RV/grabado/grabado_pre_pro.wav"
REC_RAW = f"{ ROOT }RV/grabado/raw.wav"
REC_PROC = f"{ ROOT }RV/grabado/Record1.wav"
CSV_DIR = f"{ ROOT }RV/caracteristicas_audios_dir.npz"
CSV_ACC = f"{ ROOT }RV/caracteristicas_audios_acc.npz"